[workspace]
members = [
    "esp-wifi",
    "esp-wifi-sys",
    "xtask",
]
exclude = [
    "extras/bench-server",
    "extras/esp-wifishark",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = true

[workspace.dependencies]
defmt = "=0.3.5"
esp32c3-hal = { version = "0.14.0", default-features = false }
esp32c2-hal = { version = "0.12.0", default-features = false }
esp32c6-hal = { version = "0.7.0",  default-features = false }
esp32h2-hal = { version = "0.5.0", default-features = false }
esp32-hal   = { version = "0.17.0", default-features = false }
esp32s3-hal = { version = "0.14.0", default-features = false }
esp32s2-hal = { version = "0.14.0", default-features = false }
smoltcp = { version = "0.10.0", default-features=false, features = ["medium-ethernet", "socket-raw"] }
critical-section = "1.1.1"
portable-atomic = { version = "1.5", default-features = false }
portable_atomic_enum = { version = "0.3.0", features = ["portable-atomic"] }
log = "0.4.20"
embedded-svc = { version = "0.26.1", default-features = false, features = [] }
enumset = { version = "1.1.3", default-features = false }
linked_list_allocator = { version = "0.10.5", default-features = false, features = ["const_mut_refs"] }
embedded-io = "0.6.1"
fugit = "0.3.7"
heapless = { version = "0.7.16", default-features = false }
num-derive = { version = "0.4" }
num-traits = { version = "0.2", default-features = false }
esp-wifi-sys = { version = "0.1.0", path = "../esp-wifi-sys" }
embassy-sync = { version = "0.5.0" }
embassy-futures = { version = "0.1.0" }
toml-cfg = "0.1.3"
libm = "0.2.7"
cfg-if = "1.0.0"
static_cell = { version = "2.0", features = ["nightly"] }

embassy-net = { version = "0.2.1", features = ["tcp", "udp", "dhcpv4", "medium-ethernet"] }
bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "0db8fcb", features = ["macros"] }
embassy-executor = { version = "0.4.0", package = "embassy-executor", features = ["nightly", "integrated-timers"] }
embassy-time = { version = "0.2.0" }
esp-println = { version = "0.7.0" }
esp-backtrace = { version = "0.9.0", features = ["panic-handler", "exception-handler", "print-uart"] }
embedded-hal-async = { version = "1.0.0-rc.2" }
embedded-io-async = { version = "0.6.0" }

futures-util = { version = "0.3.28", default-features = false, features = ["portable-atomic"] } # need this to activate portable-atomic on AtomicWaker even though we don't use it
atomic-waker = { version = "1.1.2", default-features = false, features = ["portable-atomic"] } # need this to activate portable-atomic on AtomicWaker used by embedded-svc even though we don't use it

[patch.crates-io]
embassy-net = { git = "https://github.com/embassy-rs/embassy.git", package = "embassy-net", rev = "14f41a71b6ea9dedb4ee5b9c741fe10575772c7d"}
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", package = "embassy-time", rev = "14f41a71b6ea9dedb4ee5b9c741fe10575772c7d"}
