[workspace]
members = [
    "esp-wifi",
    "esp-wifi-sys",
    "xtask",
    "examples-util",
    "examples-esp32c2",
    "examples-esp32c3",
    "examples-esp32c6",
    "examples-esp32",
    "examples-esp32s2",
    "examples-esp32s3",
]
exclude = [
    "extras/esp-wifishark",
]
resolver = "2"

[profile.release]
# Explicitly disable LTO which the Xtensa codegen backend has issues
lto = "off"
opt-level = 3
debug = true

[profile.dev]
# Explicitly disable LTO which the Xtensa codegen backend has issues
lto = "off"

[workspace.dependencies]
embedded-hal = "0.2.3"
esp-hal-common = { version = "0.11.0" }
esp32c3-hal = { version = "0.11.0" }
esp32c2-hal = { version = "0.9.0" }
esp32c6-hal = { version = "0.4.0" }
esp32-hal = { version = "0.14.0", features = [ "rt" ] }
esp32s3-hal = { version = "0.11.0", features = [ "rt" ] }
esp32s2-hal = { version = "0.11.0", features = [ "rt" ] }
esp32c3 = { version = "0.16.0",  features = ["critical-section"] }
esp32c2 = { version = "0.13.0",  features = ["critical-section"] }
esp32c6 = { version = "0.6.0",  features = ["critical-section"] }
smoltcp = { version = "0.10.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "proto-dns", "socket-tcp", "socket-icmp", "socket-udp", "socket-dns", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
critical-section = "1.1.1"
atomic-polyfill = "1.0.2"
log = "0.4.18"
embedded-svc = { version = "0.25.1", default-features = false, features = [] }
enumset = { version = "1", default-features = false }
linked_list_allocator = { version = "0.10.5", default-features = false, features = ["const_mut_refs"] }
embedded-io = "0.4.0"
fugit = "0.3.7"
heapless = { version = "0.7.16", default-features = false }
num-derive = { version = "0.3", features = ["full-syntax"] }
num-traits = { version = "0.2", default-features = false }
esp-wifi-sys = { version = "0.1.0", path = "../esp-wifi-sys" }
embassy-sync = { version = "0.2.0" }
embassy-futures = { version = "0.1.0" }
embassy-net-driver = { version = "0.1.0" }
toml-cfg = "0.1.3"

embassy-net = { version = "0.1.0", features = ["nightly", "tcp", "udp", "dhcpv4", "medium-ethernet"] }
bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "b82f1e7009bef7e32f0918be5b186188aa5e7109", features = ["macros"] }
embassy-executor = { version = "0.2.1", package = "embassy-executor", features = ["nightly", "executor-thread", "integrated-timers"] }
embassy-time = { version = "0.1.1", features = ["nightly"] }
futures-util = { version = "0.3.28", default-features = false }
esp-println = { version = "0.5.0", features = ["log"] }
esp-backtrace = { version = "0.7.0", features = ["panic-handler", "exception-handler", "print-uart"] }
embedded-hal-async = { version = "0.2.0-alpha.1" }
