[package]
name = "esp-wifi"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.3"
nb = "1.0.0"
void = { version = "1.0.2", default-features = false }

esp32c3-hal = { package="esp32c3-hal", git = "https://github.com/esp-rs/esp-hal", optional = true }
esp32-hal = { package="esp32-hal", git = "https://github.com/esp-rs/esp-hal", optional = true }
riscv-rt = { version = "0.8.1", optional = true }
riscv = { version = "0.8.0", optional = true }
xtensa-lx-rt = { version = "0.11.0", optional = true }
xtensa-lx = { version = "0.7.0", optional = true }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
critical-section = "0.2.7"
atomic-polyfill = "0.1.7"
log = "0.4.17"
embedded-svc = { version = "0.20.3", default-features = false, features = [ "alloc" ], optional = true }
enumset = { version = "1", default-features = false, optional = true }
esp-alloc = { git = "https://github.com/esp-rs/esp-alloc" }
embedded-io = "0.2.0"

[build-dependencies]
riscv-target = { version = "0.1.2", optional = true }

[target.xtensa-esp32-none-elf.dev-dependencies]
esp-println = { git = "https://github.com/esp-rs/esp-println.git", features = [ "esp32" ] }
esp-backtrace = { git = "https://github.com/bjoernQ/esp-backtrace.git", features = [ "esp32", "panic-handler", "exception-handler" ] }

[target.riscv32imc-unknown-none-elf.dev-dependencies]
esp-println = { git = "https://github.com/esp-rs/esp-println.git", features = [ "esp32c3" ] }
esp-backtrace = { git = "https://github.com/bjoernQ/esp-backtrace.git", features = [ "esp32c3", "panic-handler", "exception-handler" ] }

[dev-dependencies]
ble-hci = { git = "https://github.com/bjoernQ/ble-hci", branch = "embedded-io" }

[features]
default = [ "utils" ]
esp32c3 = [ "riscv-target", "riscv", "riscv-rt", "esp32c3-hal" ]
esp32 = [ "esp32-hal", "xtensa-lx-rt", "xtensa-lx" ]
wifi_logs = []
dump_packets = []
utils = [ ]
enumset = []
embedded-svc = [ "dep:enumset", "dep:embedded-svc", "utils" ]
