[package]
name = "esp-wifi"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"

[dependencies]
embedded-hal = "0.2.3"
nb = "1.0.0"
void = { version = "1.0.2", default-features = false }
esp32c3-hal = { version = "0.2.0", optional = true }
esp32-hal = { version = "0.5.0", optional = true, features = [ "bluetooth","rt" ] }
esp32s3-hal = { version = "0.2.0", optional = true, features = [ "rt" ] }
riscv-rt = { version = "0.9.0", optional = true }
riscv = { version = "0.8.0", optional = true }
xtensa-lx-rt = { version = "0.13.0", optional = true }
xtensa-lx = { version = "0.7.0", optional = true }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
critical-section = "1.1.0"
atomic-polyfill = "1.0.1"
log = "0.4.17"
embedded-svc = { version = "0.22.1", default-features = false, features = [], optional = true }
enumset = { version = "1", default-features = false, optional = true }
esp-alloc = { version = "0.1.0", features = ["oom-handler"] }
embedded-io = "0.3.0"
fugit = "0.3.6"
heapless = { version = "0.7.14", default-features = false }

[build-dependencies]
riscv-target = { version = "0.1.2", optional = true }

[dev-dependencies]
ble-hci = { git = "https://github.com/bjoernQ/ble-hci", branch = "embedded-io" }

[target.xtensa-esp32-none-elf.dev-dependencies]
esp-println = { version = "0.3.0", features = [ "esp32", "log" ] }
esp-backtrace = { version = "0.2.0", features = [ "esp32", "panic-handler", "exception-handler", "print-uart" ] }

[target.riscv32imc-unknown-none-elf.dev-dependencies]
esp-println = { version = "0.3.0", features = [ "esp32c3", "log" ] }
esp-backtrace = { version = "0.2.0" , features = [ "esp32c3", "panic-handler", "exception-handler", "print-uart" ] }

[target.xtensa-esp32s3-none-elf.dev-dependencies]
esp-println = { version = "0.3.0", features = [ "esp32s3", "log" ] }
esp-backtrace = { version = "0.2.0", features = [ "esp32s3", "panic-handler", "exception-handler", "print-uart" ] }

[features]
default = [ "utils" ]
esp32c3 = [ "riscv-target", "riscv", "riscv-rt", "esp32c3-hal" ]
esp32 = [ "esp32-hal", "xtensa-lx-rt/esp32", "xtensa-lx/esp32" ]
esp32s3 = [ "esp32s3-hal", "xtensa-lx-rt/esp32s3", "xtensa-lx/esp32s3" ]
wifi_logs = []
dump_packets = []
utils = []
enumset = []
embedded-svc = [ "dep:enumset", "dep:embedded-svc", "utils" ]
wifi = []
ble = []

# currently published versions don't contain all relevant adjustments - using git dependencies for now
[patch.crates-io]
esp32s3-hal = { git = "https://github.com/esp-rs/esp-hal/", package = "esp32s3-hal", rev = "6eea2f266a451678d244917329e2e885940fce9c" }
