[workspace]
members = [
    "esp-wifi",
    "esp-wifi-sys",
    "xtask",
    "examples-util",
    "examples-esp32c2",
    "examples-esp32c3",
    "examples-esp32c6",
    "examples-esp32",
    "examples-esp32s2",
    "examples-esp32s3",
]
resolver = "2"

[profile.release]
# Explicitly disable LTO which the Xtensa codegen backend has issues
lto = "off"
opt-level = 3

[profile.dev]
# Explicitly disable LTO which the Xtensa codegen backend has issues
lto = "off"

[workspace.dependencies]
embedded-hal = "0.2.3"
esp-hal-common = { version = "0.8.0" }
esp32c3-hal = { version = "0.8.0" }
esp32c2-hal = { version = "0.6.0" }
esp32c6-hal = { version = "0.1.0" }
esp32-hal = { version = "0.11.0", features = [ "rt" ] }
esp32s3-hal = { version = "0.8.0", features = [ "rt" ] }
esp32s2-hal = { version = "0.8.0", features = [ "rt" ] }
esp32c3 = { version = "0.13.0",  features = ["critical-section"] }
esp32c2 = { version = "0.10.0",  features = ["critical-section"] }
esp32c6 = { version = "0.3.0",  features = ["critical-section"] }
smoltcp = { version = "0.9.1", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
critical-section = "1.1.1"
atomic-polyfill = "1.0.1"
log = "0.4.17"
embedded-svc = { version = "0.23.1", default-features = false, features = [] }
enumset = { version = "1", default-features = false }
linked_list_allocator = { version = "0.10.3", default-features = false, features = ["const_mut_refs"] }
embedded-io = "0.4.0"
fugit = "0.3.6"
heapless = { version = "0.7.14", default-features = false }
num-derive = { version = "0.3", features = ["full-syntax"] }
num-traits = { version = "0.2", default-features = false }
esp-wifi-sys = { version = "0.1.0", path = "../esp-wifi-sys" }
embassy-sync = { version = "0.2.0" }
embassy-futures = { version = "0.1.0" }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "26474ce6eb759e5add1c137f3417845e0797df3a", features = ["nightly", "tcp", "udp", "dhcpv4", "medium-ethernet"] }
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy", rev = "26474ce6eb759e5add1c137f3417845e0797df3a" }

bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "daa341f4e5f40db8348886ab245f51902fccaa17" }
bleps-macros = { git = "https://github.com/bjoernQ/bleps", package = "bleps-macros", rev = "33fde67257bfbc6c0aebf7649fd302c82ed94c64" }
embassy-executor = { package = "embassy-executor", git = "https://github.com/embassy-rs/embassy/", rev = "e2516bb", features = ["nightly", "executor-thread", "integrated-timers"] }
embassy-time = { version = "0.1.0", features = ["nightly"] }
futures-util = { version = "0.3.17", default-features = false }
esp-println = { version = "0.4.0", features = ["log"] }
esp-backtrace = { version = "0.6.0", features = ["panic-handler", "exception-handler", "print-uart"] }
embedded-hal-async = { version = "0.2.0-alpha.0" }
