[package]
name = "esp-wifi"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.3"
nb = "1.0.0"
void = { version = "1.0.2", default-features = false }

esp32c3-hal = { package="esp32c3-hal", git = "https://github.com/esp-rs/esp-hal", rev = "eb47b0fe212f0cf7ce1a6564478058b2f48c2bcb", optional = true }
esp32-hal = { package="esp32-hal", git = "https://github.com/esp-rs/esp-hal", rev = "eb47b0fe212f0cf7ce1a6564478058b2f48c2bcb", optional = true }
riscv-rt = { version = "0.8.1", optional = true }
riscv = { version = "0.8.0", optional = true }
xtensa-lx-rt = { version = "0.11.0", optional = true }
xtensa-lx = { version = "0.7.0", optional = true }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
critical-section = "0.2.6"
atomic-polyfill = "0.1.7"
log = "0.4.16"
embedded-svc = { version = "0.20.3", default-features = false, features = [ "alloc" ], optional = true }
enumset = { version = "1", default-features = false, optional = true }

[build-dependencies]
riscv-target = { version = "0.1.2", optional = true }

[features]
default = [ "utils" ]
esp32c3 = [ "riscv-target", "riscv", "riscv-rt", "esp32c3-hal" ]
esp32 = [ "esp32-hal", "xtensa-lx-rt", "xtensa-lx", "critical-section/custom-impl" ]
wifi_logs = []
dump_packets = []
utils = [ ]
allocator = []
enumset = []
embedded-svc = [ "allocator", "dep:enumset", "dep:embedded-svc", "utils" ]
