[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    # "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",

    # LLD
    "-C", "linker=rust-lld",
    "-C", "link-arg=-Tlinkall.x",
    # "-C", "llvm-args=-mtext-section-literals"
]

[build]
target = "xtensa-esp32-none-elf"
 
[unstable]
build-std = [ "core" ]
