[target.riscv32i-unknown-none-elf]
runner = "espflash --speed 921600 --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Tesp32c3_rom_functions.x",

    "-C", "force-frame-pointers",
]
 
[target.xtensa-esp32-none-elf]
runner = "espflash --speed 921600 --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Tesp32_rom_functions.x",
]

[build]
target = "riscv32i-unknown-none-elf"
 
[unstable]
build-std = [ "core", "alloc" ]
