name: CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Examples:
  SSID: ""
  PASSWORD: ""
  STATIC_IP: ""
  GATEWAY_IP: ""

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: false
      - uses: Swatinem/rust-cache@v1

      - name: build (ble)
        run: cd examples-esp32 && cargo build --release --example=ble --features=ble
      - name: build (dhcp)
        run: cd examples-esp32 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32 && cargo build --release --example=embassy_esp_now --features=async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32 && cargo build --release --example=embassy_dhcp --features=async,embedded-svc,wifi,embassy-net

  esp32c2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imc-unknown-none-elf
          components: rust-src
      - uses: Swatinem/rust-cache@v1

      - name: build (ble)
        run: cd examples-esp32c2 && cargo build --release --example=ble --features=ble
      - name: build (dhcp)
        run: cd examples-esp32c2 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32c2 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32c2 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32c2 && cargo build --release --example=embassy_esp_now --features=async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32c2 && cargo build --release --example=embassy_dhcp --features=async,embedded-svc,wifi,embassy-net

  esp32c3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imc-unknown-none-elf
          components: rust-src
      - uses: Swatinem/rust-cache@v1

      - name: build (ble)
        run: cd examples-esp32c3 && cargo build --release --example=ble --features=ble
      - name: build (coex)
        run: cd examples-esp32c3 && cargo build --release --example=coex --features=embedded-svc,wifi,ble
      - name: build (dhcp)
        run: cd examples-esp32c3 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32c3 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32c3 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32c3 && cargo build --release --example=embassy_esp_now --features=async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32c3 && cargo build --release --example=embassy_dhcp --features=async,embedded-svc,wifi,embassy-net

  esp32c6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imac-unknown-none-elf
          components: rust-src
      - uses: Swatinem/rust-cache@v1

      - name: build (dhcp)
        run: cd examples-esp32c6 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32c6 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32c6 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32c6 && cargo build --release --example=embassy_esp_now --features=esp32c3-async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32c6 && cargo build --release --example=embassy_dhcp --features=esp32c3-async,embedded-svc,wifi,embassy-net

  esp32s2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s2
          ldproxy: false
      - uses: Swatinem/rust-cache@v1

      - name: build (dhcp)
        run: cd examples-esp32s2 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32s2 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32s2 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32s2 && cargo build --release --example=embassy_esp_now --features=async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32s2 && cargo build --release --example=embassy_dhcp --features=async,embedded-svc,wifi,embassy-net

  esp32s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - uses: Swatinem/rust-cache@v1

      - name: build (ble)
        run: cd examples-esp32s3 && cargo build --release --example=ble --features=ble
      - name: build (coex)
        run: cd examples-esp32s3 && cargo build --release --example=coex --features=embedded-svc,wifi,ble
      - name: build (dhcp)
        run: cd examples-esp32s3 && cargo build --release --example=dhcp --features=embedded-svc,wifi
      - name: build (static_ip)
        run: cd examples-esp32s3 && cargo build --release --example=static_ip --features=embedded-svc,wifi
      - name: build (esp_now)
        run: cd examples-esp32s3 && cargo build --release --example=esp_now --features=esp-now
      - name: build (embassy_esp_now)
        run: cd examples-esp32s3 && cargo build --release --example=embassy_esp_now --features=async,esp-now
      - name: build (embassy_dhcp)
        run: cd examples-esp32s3 && cargo build --release --example=embassy_dhcp --features=async,embedded-svc,wifi,embassy-net
